### PR TITLE
Implement automated changelog generation

### LINKED ISSUE #50: Automate a CHANGELOG
Introduce a method of automating the maintenance of a CHANGELOG. It should be easy for developers to update the CHANGELOG. It should be easy for users to find out when specific change occurred without git spelunking.

### PR DESCRIPTION
**Pull request by cwjohnston**
Closes #50

### CODE REVIEW

**Comment by cwjohnston** [comment]
@portertech travis failure relates to an unbounded github_changelog_generator dependency, activesupport, requiring Ruby >=2.2.2.

Would you like me to:

A. Pin activesupport back in Gemfile
B. Update .travis.yml to use Ruby 2.2.0 for Ruby 2.2 testing
C. Remove Ruby 2.2 testing from .travis.yml

**Comment by portertech** [comment]
@cwjohnston I do not believe we (or runtime dependencies) use activesupport in the core libraries, I am inclined to pin it back, if that works.

**Comment by cwjohnston** [comment]
@portertech I've also added a RELEASE.md to document release process.

Please note that [populating `CHANGELOG_GITHUB_TOKEN` env var with a github auth token](https://github.com/skywinder/github-changelog-generator#github-token) makes changelog generation much faster.

**Comment by portertech** [comment]
This is fantastic 👍  This PR can be considered the standard for changelog management to be applied to the other core libs.

730147c4-7560-11e4-9375-fefd2f67563b

**Pull request merged**
