### PR TITLE
Implement Transport Base API hostname resolution methods

### PR DESCRIPTION
**Pull request by portertech**
This pull request adds DNS hostname resolution methods to the Transport Base API, allowing Sensu Transports to resolve hostname prior to attempting to connect to a host.

### CODE REVIEW

**Comment by cwjohnston** [comment]
Closes #39 in so far as RabbitMQ transport is concerned. We'll also need to implement similar functionality into sensu-redis for the Redis transport.

**Comment by portertech** [comment]
Finally working, we're ready for some manual Sensu process testing :+1: JRuby tests still have intermittent failures, not sure what that is about. We can go ahead and cut a transport release for 0.27.

**Comment by portertech** [comment]
Closes https://github.com/sensu/sensu-transport/issues/35

**Comment by amdprophet** [comment]
👍

**Pull request merged**
