### PR TITLE
Use separate RabbitMQ connections for publish and subscribe

### PR DESCRIPTION
**Pull request by portertech**
Closes https://github.com/sensu/sensu-transport/issues/61

### CODE REVIEW

**Comment by amdprophet** [comment]
https://github.com/sensu/sensu-em/pull/13 fixes the exception we are seeing when running these changes under JRuby.

**Comment by portertech** [comment]
We have tested these changes in a production environment. These changes allow RabbitMQ flow control to work with Sensu as advertised 👍

**Comment by portertech** [comment]
These changes will double the number of RabbitMQ connections in every environment.

**Pull request merged**
